# To make the build reproducible, we fix the kernel headers
# version, but leave opportunity to update it.
KVER ?= v5.4

# NOTE: don't change this unless you're sure what you're doing
#	cause by this tag the dependent components refer to the current
#	component
DOCKER_OUT_IMAGE_TAG = iccom
DOCKER_OUT_TEST_IMAGE_TAG = iccom-test

.PHONY: test docker-image

default: docker-image

# This will build the reusable Docker Stage for
# other components to build the external kernel modules
docker-image:
	cd $$PWD && scripts/docker_build_wrapper.sh 	     \
					--build-arg kernel_version=${KVER}	\
					--tag ${DOCKER_OUT_IMAGE_TAG}		\
					--target ${DOCKER_OUT_IMAGE_TAG}	\
					.					\
		&& echo "docker-image: \033[0;32mOK\033[0m"

# test if the image is really working
test: docker-image
	cd $$PWD && scripts/docker_build_wrapper.sh				\
					--build-arg kernel_version=${KVER}	\
					--tag ${DOCKER_OUT_TEST_IMAGE_TAG}	\
					--tag ${DOCKER_OUT_TEST_IMAGE_TAG}	\
					--progress=plain			\
					.					\
		&& echo "test: \033[0;32mOK\033[0m"

# Will remove the docker image generated by the build
# and all dangling images as well
clean-docker-images:
	docker rmi ${DOCKER_OUT_IMAGE_TAG} || true
	docker rmi ${DOCKER_OUT_TEST_IMAGE_TAG} || true
	docker image prune
	docker system prune

print-output-docker-image-tag:
	@echo "${DOCKER_OUT_IMAGE_TAG}"